Added RentalController, properties to correct time format input/output, added util method for correct data display in setActualReturnDate method response.
RadiALo/car-sharing-service pull request #25
Opened 2023-05-30 15:52 UTC by RandomEastEcho

2023-05-30 18:13 UTC, pechivo approved these changes

2023-05-31 07:47 UTC, VitaliiPotseluiko requested changes

2023-05-31 07:47 UTC, VitaliiPotseluiko commented on src/main/java/com/carsharing/controller/RentalController.java
> +    }
```suggestion
    @GetMapping("/by-user-id/{id}")
    public List<RentalResponseDto> findByUserId(@PathVariable Long id) {
        return rentalService.getByUserId(id)
                .stream()
                .map(responseMapper::fromModel)
                .collect(Collectors.toList());
    }
```

2023-05-31 07:47 UTC, VitaliiPotseluiko commented on src/main/java/com/carsharing/controller/RentalController.java
> +    @PostMapping("/{id}/return/")
```suggestion
    @PostMapping("/{id}/return")
```

2023-05-31 08:55 UTC, VitaliiPotseluiko approved these changes

2023-05-31 09:04 UTC, merged