added validation of invertory in TG notifications
RadiALo/car-sharing-service pull request #43
Opened 2023-06-05 13:05 UTC by VitaliiPotseluiko

2023-06-05 13:54 UTC, Yehor-Cherkashyn requested changes

2023-06-05 13:54 UTC, Yehor-Cherkashyn commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create
There should be validate ((
The easiest way to write create, but not right )))

2023-06-05 13:54 UTC, Yehor-Cherkashyn commented on src/main/resources/application.properties
> +spring.jackson.date-format=yyyy-MM-dd
What are these properties for? (Maybe it's right, but I don't understand)

2023-06-06 06:58 UTC, RandomEastEcho approved these changes

2023-06-06 07:22 UTC, pechivo approved these changes

2023-06-06 07:56 UTC, Yehor-Cherkashyn approved these changes

2023-06-06 07:57 UTC, merged