Implemented tests for car service
RadiALo/car-sharing-service pull request #50
Opened 2023-06-09 06:51 UTC by RandomEastEcho

2023-06-09 07:02 UTC, Yehor-Cherkashyn requested changes

2023-06-09 07:02 UTC, Yehor-Cherkashyn commented on src/test/java/com/example/carsharing/service/CarServiceImplTest.java
> +        Car car = new Car();
Create the @BeforeAll method for creating the car. You do it in the all tests.

2023-06-09 07:02 UTC, Yehor-Cherkashyn commented on src/test/java/com/example/carsharing/service/CarServiceImplTest.java
> +        Car car = new Car();
The same

2023-06-09 07:02 UTC, Yehor-Cherkashyn commented on src/test/java/com/example/carsharing/service/CarServiceImplTest.java
> +        Car car = new Car();
The same

2023-06-09 07:32 UTC, Yehor-Cherkashyn approved these changes

2023-06-12 05:53 UTC, pechivo approved these changes

2023-06-12 06:25 UTC, merged