Implemented tests for User service
RadiALo/car-sharing-service pull request #54
Opened 2023-06-11 09:05 UTC by RandomEastEcho

2023-06-12 05:52 UTC, pechivo approved these changes

2023-06-14 12:10 UTC, Yehor-Cherkashyn requested changes

2023-06-14 12:10 UTC, Yehor-Cherkashyn commented on src/test/java/com/example/carsharing/service/UserServiceImplTest.java
> +        Assertions.assertEquals("changedPassword", testUser.getPassword());
цей тест буде 100% видавати правильний результат, бо тут перевіряється не юзер із бази даних, а юзер, якому тільки но змінили поле паролю. Треба перевіряти юзера із БД (шукати цього юзера по айді наприклад).

2023-06-19 06:35 UTC, Yehor-Cherkashyn approved these changes

2023-06-19 13:22 UTC, merged