Implemented tests for Payment strategy payments.
RadiALo/car-sharing-service pull request #57
Opened 2023-06-12 09:09 UTC by RandomEastEcho

2023-06-14 12:33 UTC, Yehor-Cherkashyn requested changes

2023-06-14 12:33 UTC, Yehor-Cherkashyn commented on src/test/java/com/example/carsharing/service/PaymentStrategyFineTest.java
> +        testRental.setRentalDate(LocalDate.now());
LocalDate.now треба заміняти. Бо кожного разу може видавати різний результат, і не зрозуміло що це за дата перевіряється.

2023-06-14 12:33 UTC, Yehor-Cherkashyn commented on src/test/java/com/example/carsharing/service/PaymentStrategyFineTest.java
> +        Assertions.assertEquals(BigDecimal.valueOf(-500),
Чому -500?

2023-06-14 12:33 UTC, Yehor-Cherkashyn commented on src/test/java/com/example/carsharing/service/PaymentStrategyPaymentTest.java
> +        testRental.setRentalDate(LocalDate.now());
Теж саме

2023-06-14 12:33 UTC, Yehor-Cherkashyn commented on src/test/java/com/example/carsharing/service/PaymentStrategyPaymentTest.java
> +        testRental.setActualReturnDate(LocalDate.now());
Теж саме (не треба ставити LocalDate.now)

2023-06-14 12:33 UTC, Yehor-Cherkashyn commented on src/test/java/com/example/carsharing/service/PaymentStrategyPaymentTest.java
> +        Assertions.assertEquals(BigDecimal.valueOf(-500),
Чому -500? (чому саме мінус)?

2023-06-16 09:49 UTC, pechivo approved these changes

2023-06-19 06:36 UTC, Yehor-Cherkashyn approved these changes

2023-06-19 13:22 UTC, merged