Implemented tests for Rental controller
RadiALo/car-sharing-service pull request #61
Opened 2023-06-12 12:59 UTC by RandomEastEcho

2023-06-14 07:34 UTC, pechivo approved these changes

2023-06-14 07:34 UTC, pechivo approved these changes

2023-06-14 12:52 UTC, Yehor-Cherkashyn requested changes

2023-06-14 12:52 UTC, Yehor-Cherkashyn commented on src/test/java/com/example/carsharing/controller/RentalControllerTest.java
> +        rentalResponseDto.setUserId(testRental.getUser().getId());
код дублюється. Додай ініціалізацію в блок біфор.

2023-06-14 12:52 UTC, Yehor-Cherkashyn commented on src/test/java/com/example/carsharing/controller/RentalControllerTest.java
> +        Assertions.assertEquals(responseDtoList, result);
не консистентні нейміни (краще назви не резалт, а actualResponseDtoList, як в попередньому тесті, і в інших тестах)

2023-06-14 12:52 UTC, Yehor-Cherkashyn commented on src/test/java/com/example/carsharing/controller/RentalControllerTest.java
> +        Assertions.assertEquals(rentalResponseDto, result);
Теж саме. Назви result так само, як в інших тестах, для консистентності

2023-06-19 10:41 UTC, Yehor-Cherkashyn approved these changes

2023-06-19 13:22 UTC, merged